### PR TITLE
Rancher public dns provider

### PR DESCRIPTION
**Pull request by prachidamle**
This PR introduces a new provider "RancherPublicDNS" under /external-dns/providers

This provider integrates with the rancher_public_dns service and manages the DNS records on AWS Route53 zone hosted by Rancher for public use. 

Following environment variable needs to be set to point to the rancher_public_dns service
export RANCHER_PUBLIC_DNS_URL=http://localhost:8089/v1-rancher-dns/

To use this provider build and run 
./external-dns -debug=true -provider=RancherPublicDNS

### CODE REVIEW

**Comment by alena1108** [comment]
@prachidamle could you split it into 2 commits - one with godeps changes, and another with code changes? Would be easier to review this way

**Comment by prachidamle** [comment]
@alena1108 I have done the split, you should see 2 separate commits now

**Comment by prachidamle** [comment]
@alena1108, added changes due to move of the dns client out of go-rancher to rancher_public_dns

All commits are separate for better readability during review. Will squash once reviewed

**Comment by prachidamle** [comment]
@alena1108 where is client info?

**Comment by prachidamle** [comment]
@alena1108 Can you review the latest commits in the PR. All commits are separated for better readability during review.

**Comment by prachidamle** [comment]
@alena1108 submitted new commit with review changes suggested

**Comment by prachidamle** [comment]
@alena1108 submitted the dnsToken -> serviceToken naming change

**Comment by jhmartin** [comment]
Can this be moved forward?

**Comment by janeczku** [comment]
Closing this due to inactivity/not-needed

**Pull request closed without merging**
