### PR TITLE
Adding Vultr DNS provider

### PR DESCRIPTION
**Pull request by bfosberry**
tested, looks good

### CODE REVIEW

**Comment by bfosberry** [comment]
I did further testing with this and tried to run it:

```
1/6/2017 4:58:14 PMtime="2017-01-07T00:58:14Z" level=fatal msg="Failed to get provider 'vultr': Failed to list records for 'mydomain.com': Get https://api.vultr.com/v1/dns/records?domain=mydomain.com&api_key=MYSUPERSECRETKEY: x509: failed to load system roots and no roots provided"
```

Im guessing Im returning the records from the provider in a format that cant be used. Anyone know what Im doing wrong?

**Comment by janeczku** [comment]
Hi @bfosberry. Looks like the Docker image you are running this in is missing CA certificates?

**Comment by superseb** [comment]
Any updates here @bfosberry ?

**Comment by bfosberry** [comment]
I had totally forgotten about this, but am playing with vultr and rancher again, so I'll take a look. thanks!

**Comment by alena1108** [comment]
Thank you for your contribution, but with the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches

**Pull request closed without merging**
