### PR TITLE
Updated DigitalOcean library, added support for per record TTL.

### PR DESCRIPTION
**Pull request by SamMousa**
I've never written anything in GOLANG, so please look at my changes carefully.

This PR solves https://github.com/rancher/rancher/issues/9785

As far as I can tell it works.. :)

### CODE REVIEW

**Comment by vincent99** [comment]
Ping @janeczku --^

 FWIW Jan and Prachi are both employees so those PRs not sitting for lack of review...

**Comment by SamMousa** [comment]
@vincent99, ah, I couldn't clearly see that :)

Thanks for the prompt response!

**Comment by superseb** [comment]
Thanks for the PR! Just needs a `go fmt`, can you update it?

Ran this container using TTL 260 and TTL 1, updated the records correctly, removed it correctly.

**Comment by SamMousa** [comment]
I've done it for the source file, not the vendor file(s).

**Comment by alena1108** [comment]
Thank you for your contribution, but with the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches

**Pull request closed without merging**
