### PR TITLE
added support for powerdns4

### PR DESCRIPTION
**Pull request by dmportella**
Support for powerdns provider is called powerdns4 uses the same details of powerdns provider

Closes rancher/rancher#6136

### CODE REVIEW

**Comment by janeczku** [comment]
@dmportella Much appreciated, i hope to find bandwidth to review and merge this soon! 😅

**Comment by dmportella** [comment]
thanks hope all is oke with it (assume it is since it been merged)

**Comment by janeczku** [comment]
Hey there @dmportella, i had to revert it because a bug in the upstream package (`github.com/dmportella/powerdns`) as well as an incorrect import in the provider prevented building. If you are able to fix this please open a new PR so we can land this!

Typo in package:

```bash
~/go/src/github.com/rancher/external-dns  go build
# github.com/dmportella/powerdns
../../dmportella/powerdns/powerdns.go:40: unknown field 'Http' in struct literal of type Client
```

Incorrect import reference ([package names really should be lowercase](https://blog.golang.org/package-names)):

```
~/go/src/github.com/rancher/external-dns  go build
# github.com/rancher/external-dns/providers/powerdns4
providers/powerdns4/powerdns4.go:9: imported and not used: "github.com/dmportella/powerdns" as PowerDNS
providers/powerdns4/powerdns4.go:15: undefined: powerdns in powerdns.Client
```

**Comment by dmportella** [comment]
thx i will fix that

**Comment by dmportella** [comment]
@janeczku fixed the two issues on here

**Pull request merged**
