### PR TITLE
powerdns4 updated

### PR DESCRIPTION
**Pull request by dmportella**
Fixed issues on the repo so now package powerdns is in lowercase and the http field is case correctly

### CODE REVIEW

**Comment by dmportella** [comment]
@janeczku not sure why its has a conflict but it should all be working now

**Comment by narbutas** [comment]
so when we can expect to get PowerDNS4 support?

**Comment by dmportella** [comment]
@narbutas its already done just need to be accepted into main line.

**Comment by areian** [comment]
Any updates on when we will see this merged?

**Comment by dmportella** [comment]
Yeah I been waiting for a bit now. not sure when rancher dev is going to look at it again
all the problems they mentioned have been resolved.

**Comment by dmportella** [comment]
I am currently using the provider i worked on - have been for 4 months now with no issues

**Comment by deniseschannon** [comment]
Closing in favor of #80

**Comment by dmportella** [comment]
This has been working for months awaiting to be reviewed and merged I had no responses. Oh well wasted effort. Anyway glad someone finally engaged and merged something.

**Pull request closed without merging**
