### PR TITLE
Infoblox limits on healthcheck and zone

### PR DESCRIPTION
**Pull request by superseb**
https://github.com/rancher/rancher/issues/10117

https://gist.github.com/superseb/9bf843e6a2e82e8cf9f60ce350b7af82

### CODE REVIEW

**Comment by aiwantaozi** [comment]
@yasker This PR is about infoblox DNS provide, it look well, could you help review this, please?
More info, infoblox have conception zone, a record A or TXT could belong to the different zone, and we let user config zone when enabling the infoblox DNS.

**Comment by yasker** [comment]
@superseb Are the PR ready? If so, can you remove the `WIP` sign? 

Otherwise LGTM.

@aiwantaozi Can you review the logic part?

**Comment by superseb** [comment]
@yasker Just to clarify, this PR adds limits on the amount of records that is retrieved by the healthcheck. And it isolates the actions to the configured zone. I stumbled upon this when I was investigating https://github.com/rancher/rancher/issues/10117.

This is not a 100% solution as the record limit of 1000 in 1 zone is still valid, we need to build pagination in the request for the DNS records but this would require more work and maybe a different library. And these changes need to be done anyway.

**Comment by yasker** [comment]
@superseb Got it. Moreover, I noticed that we do limit to the zone when `GetRecords` but not in `findRecords` (which has been used by `RemoveRecord`). If we're going to limit every operation in the same zone, then the user may able to `RemoveRecord` in a different zone, even they cannot see it by using `GetRecords`?

**Comment by superseb** [comment]
@yasker Updated for `findRecords`

**Comment by yasker** [comment]
LGTM.

**Comment by yasker** [comment]
@superseb v0.7.8 has been released, you can make a PR to the catalog now.

**Pull request merged**
