### PR TITLE
make sure extra records dont get dropped

### PR DESCRIPTION
**Pull request by nlf**

### CODE REVIEW

**Comment by alena1108** [comment]
@nlf @janeczku one more proof that we need tests :) At least for providers part. Can be done by:

* implementing simulator clients for each provider
* generate static dns records content for each simulator client
* positive test for provider.getRecords - validate that the data returned is aligned with the static dns records content
* positive/negative tests for add/remove records - add record that never existed, try to add duplicated record, remove non-existing record, remove existing record, etc

I'm open for other test design solution/suggestions.

**Comment by alena1108** [comment]
As for the PR itself, LGTM

**Comment by janeczku** [comment]
@alena1108 As Konfuzius said: Writing tests proofs the most valuable when you haven't done it. :hushed:

I actually did quite intensive manual testing of the methods in the Cloudflare provider by implementing them in a command line package and writing/querying to/from the live API. So i am quite confident at this point. But i still see the need for written tests while the code may evolve in the future. I think something in the line what you proposed makes a lot of sense. I may add that once we have a simulator client for one provider it should be easily adaptable for the others :wink:

**Comment by janeczku** [comment]
@alena1108 To make testing for the providers, we either need a test with a mock MetadataClient in "github.com/rancher/external-dns/metadata" or move all providers in separate packages.

**Comment by alena1108** [comment]
@janeczku 

I prefer to test providers in isolation first, w/o metadata involved. So my vote goes to your second proposal. Thank you for helping out!

**Pull request merged**
