### PR TITLE
Added Support for Toggling DNS via Labels

### PR DESCRIPTION
**Pull request by seglberg**
## Add Support for Toggling DNS via Labels

We needed more control over how external DNS was actually creating records, for example, we needed to be able to disable it on a per-host basis. We also needed to allow DNS entries to be made for containers that did not have ports exposed (but are reachable through our load-balancer).

Resolves rancher/rancher#7046

### Details

New Labels for Controlling External DNS. Notice that the label is to `disable` external DNS. This is so the current/original behavior is observed when the external DNS service is upgraded for existing deployments.

1. Host:      io.rancher.host.external_dns.disable=[default: no]
2. Service:   io.rancher.service.external_dns.disable=[default: no]

  These two labels completely turn off external DNS at the host/service level.

3. Container: io.rancher.container.external_dns.force

  This label acts differently depending on if it is set to yes, no, or unset.

  - If set to `yes`, external DNS is forced for the container, regardless if it has exposed ports.
  - If set to `no` the container effectively disables external DNS for itself.
  - If the label is not set, the original behavior is observed.

---
This change is [Reviewable](https://reviewable.io/reviews/rancher/external-dns/51)

### CODE REVIEW

**Comment by alena1108** [comment]
@janeczku could you please review?

**Comment by vincent99** [comment]
Negative booleans (disabled: false) are confusing to talk about, you can have a positive option that just defaults to true if not present:

io.rancher.host.external_dns=true/false (default: true) 

We also usually explicitly look for the string "true" or "false" rather than accepting undocumented various truthy yaml words.

I don't see why the container option is separate from the service one.. The whole loop applies to the containers of a service. Are you trying to allow excluding individual containers that somehowhave different labels within a single service?

Options which behave differently if not present are also confusing, each behavior should have a value and one of them should be the default.

So it sounds to me like service+container is one option:

io.rancher.service.external_dns=always/auto/never (default: auto)

And then the docs explain what the 3 values mean in detail.

**Comment by seglberg** [comment]
Thanks for the quick feedback!

In regards to the service vs container labels, as you guessed, the intention was to exclude a single container from the service. However, after thinking it through, its usefulness is pretty limited.

---
Outstanding Changes:

- [ ] Remove Negative Booleans. I agree that negative booleans are confusing. We had switched in an earlier version of our changes, so I will change that back.
- [ ] Match the Strings "true"/"false" Explicitly (to match convention elsewhere in Rancher).
- [ ] Make Service Level Option Ternary
- [ ] Remove Container Level Option

**Comment by seglberg** [comment]
Pushed changes to address the previous comments. Let me know if there are any additional concerns/comments. :+1:

**Comment by vincent99** [comment]
LGTM

**Comment by janeczku** [comment]
@seglberg Could you explain how you intend to use `io.rancher.service.external_dns=always` with load balanced containers that have no ports exposed? This will create a DNS record set with the IP addresses of the hosts on which the load balanced containers are running on. Wouldn't you rather want the IP addresse(s) of the hosts on which the load balancer is running on?

**Comment by InAnimaTe** [comment]
@janeczku Yeah so we actually have a usecase where we're deploying our own Load Balancer that listens on 80/443 and for each customer, we setup DNS etc.. that needs to point to the node their container(s) are currently running on. This also helps for other installations where there might be authentication or other sorts of proxying being handled in front of the app.

**Comment by janeczku** [comment]
> we're deploying our own Load Balancer that listens on 80/443 and for each customer, we setup DNS etc.. that needs to point to the node their container(s) are currently running on

Just so that i understand that right: For each customer container's are running on a specific node and on each of the customer nodes you have a load balancer that proxies stuff just for the containers on that same host?

**Comment by InAnimaTe** [comment]
Correct ;) Local Load Balancing for only the containers running on that specific host.

**Comment by janeczku** [comment]
Generally i would prefer DNS record creation for load balanced services to be implemented in such way that it is not limited to the (edgy) scenario where containers are scheduled to run on the same host as the load balancer. With the v1.2 metadata service exposing load balancer configuration we can create DNS records for every service targeted by a rule in the LB config.

I guess we can still add the `io.rancher.service.external_dns=always/auto/never` just have to make sure that users understand the limitation of it.

**Comment by InAnimaTe** [comment]
I know you guys are more tuned to how Enterprises manage and solve the problems they're having. I guess we're working on more of a cloud based SaaS platform so our challenges are a bit different. In that realm, I disagree that is really an "edgy" scenario. Rancher has labels for other functions that extend functionality not exactly "normal" in most cases. This is because of the wide range of uses an awesome container orchestration platform can provide ;)

I'd be up for writing a few stanza's of documentation around this functionality to make sure its absolutely clear whats going on. Of course, we aren't changing the default functionality in any way; using a label only adds to the abilities of this service, nothing else.

Either way, we decided to include this because we needed it and thought committing it upstream would be helpful. No worries here if you guys decide to not include it. That's the beauty of Open Source ;)

**Comment by janeczku** [comment]
Appreciate your contribution @InAnimaTe !

**Pull request merged**
