### PR TITLE
Add OVH provider

### PR DESCRIPTION
**Pull request by stephane-monnot**
- Related to rancher/community-catalog#750
- Fix rancher/rancher#8735

Tested with : 
 - my community catalog fork https://github.com/stephane-monnot/community-catalog.git   on master
 - my public docker image : nanoka/rancher-external-dns:latest

### CODE REVIEW

**Comment by alena1108** [comment]
@stephane-monnot looks like only vendor.conf got changes, but there are no vendor dependencies updates for ovh. You should run trash (https://github.com/rancher/trash) to pull them in. And on our side, the Drone build should be fixed to catch this type of thing in CI

**Comment by stephane-monnot** [comment]
Done. I am used to ignore vendor.

**Comment by alena1108** [comment]
@stephane-monnot could you exclude trash.lock from the commit?

**Comment by stephane-monnot** [comment]
Done. I tried to rebase with master, but I got some errors with the package dnssimple. It seems to be missing.

**Comment by alena1108** [comment]
@stephane-monnot thanks!

**Pull request merged**
