### PR TITLE
Godeps update for crackcomm/cloudflare

### PR DESCRIPTION
**Pull request by sdurrheimer**
Fixes rancher/rancher#4482
I didn't test out in a full rancher context, but locally it doesn't complain when registering my CloudFlare domain.
```bash
$ ./bin/external-dns
INFO[0000] Configured CloudFlare with zone "poxy.fr"
INFO[0000] DNSIMPLE_TOKEN is not set, skipping init of DNSimple provider
INFO[0000] GANDI_APIKEY is not set, skipping init of Gandi provider
INFO[0000] POINTHQ_TOKEN is not set, skipping init of PointHQ provider
FATA[0032] Failed to configure rancher-metadata: Error 403 accessing /version path
```

### CODE REVIEW

**Comment by janeczku** [comment]
I just executed some test cases against this PR in Rancher server v1.0.1:
Add exposed service - PASS
Scale up service - PASS
Scale down service - PASS
Remove service - PASS

LGTM 👍

**Comment by sdurrheimer** [comment]
Any news ?

**Comment by alena1108** [comment]
LGTM

**Comment by alena1108** [comment]
@sdurrheimer is there a corresponding community-catalog PR? The image would be tagged with v0.4.0

**Comment by sdurrheimer** [comment]
@alena1108 I haven't done a community-catalog PR, but I can have a look if necessary.

**Comment by alena1108** [comment]
@sdurrheimer thank you, I've just published the release, and pushed v0.4.0 image. The new catalog item should be the same as the previous one, except for the image tag.

**Pull request merged**
