### PR TITLE
Added Load Balancer Functionality

### PR DESCRIPTION
**Pull request by Jreynolds97**
Prior, the load balancer hostname field wasn't expanded by the external dns plugin, this solves that, expanding the hostname stored in the portrules portion of the metadata and assigning that to an fqdn and registering an A entry with that name. 

Behavior:
When ending a hostname with .\*, that hostname is placed as is before the requested domain name. EX: something.proxy.\* --> something.proxy.requested.domain.name

When ending a hostname with anything else, it will use the template to create a hostname using that. EX: something.proxy --> something-proxy.stack.environment.requested.domain.name
EX: something.proxy... --> something-proxy.stack.environment.requested.domain.name

### CODE REVIEW

**Comment by Jreynolds97** [comment]
Need to make minor changes to code, will reopen at a later date

**Comment by Jreynolds97** [comment]
Reopening with new changes

**Comment by superseb** [comment]
Needs import of `regexp` and `go fmt`, how did you test this?

@janeczku Is this solving the same use-case as https://github.com/rancher/rancher/issues/7703? I would rather see the loadbalanced services getting linked to the LB then propagate DNS records from LB rules. But maybe I'm missing something here.

**Comment by Jreynolds97** [comment]
@superseb I believe it is/was solving the same issue as that ticket. I've now modified it to create them as CNAME's instead of A names, and have also added another field to external-dns.go to allow for the recognizing of CNAME's coming back to prevent logs like this: 

`12/1/2017 3:11:11 PMtime="2017-12-01T22:11:11Z" level=info msg="Adding dns record: {LoadBalancer01 LoadBalancer01 {spectraserver-dev.tools-dev.charterlab.com. [x.x.x.x] A 60}}"
12/1/2017 3:12:11 PMtime="2017-12-01T22:12:11Z" level=info msg="Adding dns record: {LoadBalancer01 LoadBalancer01 {spectraserver-dev.tools-dev.charterlab.com. [x.x.x.x] A 60}}"
12/1/2017 3:13:11 PMtime="2017-12-01T22:13:11Z" level=info msg="Adding dns record: {LoadBalancer01 LoadBalancer01 {spectraserver-dev.tools-dev.charterlab.com. [x.x.x.x] A 60}}"
12/1/2017 3:14:11 PMtime="2017-12-01T22:14:11Z" level=info msg="Adding dns record: {LoadBalancer01 LoadBalancer01 {spectraserver-dev.tools-dev.charterlab.com. [x.x.x.x] A 60}}"`

repeated every minute as the TTL is still 1 minute for the CNAME entries. The new changes made should, and have, work for routing loadbalancer requested hosts to the proper place via a CNAME. I've also removed a bug in my prior code that allowed for expansion of empty host names, which caused an even larger issue.

As far as testing goes, I've essentially done testing through trial, since there aren't any automated tests anywhere in the files so far, so I didn't know the way testing was done on this project. If you have an example test, even for some other function, that you would like to send me so that I might emulate that test, I would be more than happy to write an automated test for this change.

**Comment by chris-scentregroup** [comment]
Any updates on this one? Trying to also understand entirely what it does. Documentation?

**Comment by alena1108** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches

**Pull request closed without merging**
