### PR TITLE
PowerDNS provider with v4.x support

### PR DESCRIPTION
**Pull request by waynz0r**
Unified support for v3.x and v4.x versions of PowerDNS

### CODE REVIEW

**Comment by prachidamle** [comment]
LGTM

**Comment by deniseschannon** [comment]
@waynz0r @dmportella @narbutas @areian I've released external-dns:v0.7.1 with the updates for PowerDNS. 

If someone adds a catalog item into the community-catalog, I can review and help release it. https://github.com/rancher/community-catalog/tree/master/infra-templates/powerdns-external-dns

**Comment by dmportella** [comment]
Nice one

**Comment by waynz0r** [comment]
Thanks!

@deniseschannon I created a PR for the community-catalog.

**Pull request merged**
