### PR TITLE
Powerdns 4.0 support

### PR DESCRIPTION
**Pull request by dmportella**
Hello I have added support for powerdns 4.0

Updated the existing provider to work with powerdns 4.0 this is not a backwards compatible change.

Closes rancher/rancher#6136

### CODE REVIEW

**Comment by janeczku** [comment]
@dmportella Does this still support powerdns 3.x ?

**Comment by dmportella** [comment]
> Updated the existing provider to work with powerdns 4.0 this is not a backwards compatible change.

I am working on an update at the moment that will. Please dont merge this yet

**Comment by dmportella** [comment]
Also I have identified a few issues with the general dns integration (outside of powerdns) in rancher i will raise issues with those separately.

**Comment by dmportella** [comment]
updated the pull request 

@janeczku this version supports 3 and 4 api.

there is a know issue that currently rancher is not creating records correctly (not powerdns) 

when rancher tries to create a TXT it is not adding the content with quotes as per TXT specification so powerdns correctly rejects it. (I have for now added the quotes)

there is a larger problem tho the process of checking if a record already exists is not working right (need to update the code) but the outcome is not a breaking change all it does is add the records again... eg keeping it fresh. not a desired outcome but I will address it when i have the time.

just to be clear i have tested this with the latest rancher server and with powerdns 4.

I have not tested with 3 yet.

Anyone wanting to have a try be my quest.

**Comment by janeczku** [comment]
Thanks for the update @dmportella. Is there any chance you could test against v3 API?

> when rancher tries to create a TXT it is not adding the content with quotes as per TXT specification so powerdns correctly rejects it. (I have for now added the quotes)

Whether the TXT content should be wrapped in literal quotes depends entirely on the DNS provider API. If a provider expects those then they must be added in the specific provider implementation.

**Comment by dmportella** [comment]
I havent forgotten this I am planning to revert all the changes and then create a new provider "powerdns4" separate from the old stuff so there is no need to impact existing users of the module.

**Comment by janeczku** [comment]
@dmportella +1 for creating a powerdns4 provider

**Comment by dmportella** [comment]
I am goign to close this PR and recreate it as a separate provider

**Comment by jesstruck** [comment]
could you link to the new issue/ PR when it's done ??

**Comment by dmportella** [comment]
yes of course

**Comment by dmportella** [comment]
@jesstruck All done you cans see the pull request here: rancher/external-dns/pull/64
@janeczku created a new provider for powerdns4 only so the version 3 is left alone unchanged.

**Pull request closed without merging**
