### PR TITLE
Switch route53 provider to the official AWS SDK

### PR DESCRIPTION
**Pull request by janeczku**
* Fixes https://github.com/rancher/rancher/issues/3257
* Fixes blocking issue for accounts with many zones
(only the first 100 zones where parsed)
* Fixes use of arbitrary zone when there are multiple zones with the same name in the account. Zone can now optionally be specified by setting `ROUTE53_ZONE_ID` environment variable. This also closes https://github.com/rancher/rancher/issues/4262.

### CODE REVIEW

**Comment by alena1108** [comment]
@janeczku thank you! Is there a corresponding catalog PR? I'm going to version next external dns release as v0.4.0

**Comment by janeczku** [comment]
@alena1108 Yes there is 😄  https://github.com/rancher/rancher-catalog/pull/145

Note, that i pushed an additional patch the let's users specify the hosted zone ID in case that there are multiple zones for same domain name (e.g. one private, one public). Currently we would arbitrarily use the first zone matching the name in the list returned by the API.

**Comment by alena1108** [comment]
@janeczku 

> Note, that i pushed an additional patch the let's users specify the hosted zone ID

 :thumbsup: you rock

Could you share what kind of tests you've executed against your PR? Something like: added service with port exposed, made sure it got programmed to route53. Scaled up the service, made sure one more IP was added to the A record. Scale down, service remove, etc.

I'm going to test this PR locally myself sometime early next week.

**Comment by janeczku** [comment]
@alena1108 
Tested:
* Added service with exposed port and made sure IP was added to A record
* Removed service with exposed port and made sure IP was removed from A record
* Start service with hosted zone name
* Start service with hosted zone name and hosted zone id

Not tested:
* Scaling

**Comment by alena1108** [comment]
@janeczku sorry for delay with releasing the image, got swamped by other projects and couldn't test those extra use cases for scale. Any chance you could test the scale up/down scenarios locally? If that works, I'll release.

**Comment by janeczku** [comment]
@alena1108 NP. I'll do the scaling test case tomorrow (now :sleeping:-time on this side of the pond).

**Comment by alena1108** [comment]
@janeczku thank you :)

**Comment by janeczku** [comment]
@alena1108 see amended tests above: https://github.com/rancher/external-dns/pull/31#issuecomment-206990537

**Comment by alena1108** [comment]
LGTM

**Pull request merged**
