### PR TITLE
Add support for PointHQ DNS

### PR DESCRIPTION
**Pull request by haswalt**
This add support for using PointHQ for managing automated DNS from Rancher.

### CODE REVIEW

**Comment by haswalt** [comment]
I need a little help with updating the deps as I can't get it to update properly (new to go). Any help would be great.

**Comment by haswalt** [comment]
These last few updates were added since testing this thoroughly on my own stack which now handles DNS updates correctly with the PointHQ API.

Any chance someone can look at this? @alena1108 or @cloudnautique

**Comment by cdrx** [comment]
+1

**Comment by alena1108** [comment]
@haswalt LGTM, could you squash the commits? Also do we have a PR for corresponding catalog item?

**Comment by haswalt** [comment]
@alena1108 there will be shortly. Trying to source a decent quality logo from pointHQ. 

Dor catalog should I target external-dns image version 0.1.10. Ie the next image version?

**Comment by alena1108** [comment]
@haswalt yes, you should point it to the next version. I'll make a new release some time tomorrow.

**Comment by haswalt** [comment]
@alena1108 Thanks. I've squashed my commits and i've also submitted a PR for the catalog:

https://github.com/rancher/rancher-catalog/pull/75

**Comment by alena1108** [comment]
@haswalt awesome, thx, will review

**Pull request merged**
