### PR TITLE
Throttle DNSimple API calls

### PR DESCRIPTION
**Pull request by janeczku**
Depends on https://github.com/rancher/external-dns/pull/46

### CODE REVIEW

**Comment by weppos** [comment]
@janeczku I see the `UpdateRecord` is not throttled, and it looks like it's not because you remove and re-add the record.

However, this results in 2 API calls. I wonder, any reason to not use the `UpdateRecord` API call?
https://github.com/weppos/dnsimple-go/blob/master/dnsimple/domains_records.go#L100

**Comment by janeczku** [comment]
@weppos 
`utils.DnsRecord` is effectively an RRSet, so whoever implements `provider.UpdateRecord(record utils.DnsRecord)` must operate on the RRSet and not a specific single record.
Since the API doesn't have a method to update an entire RRSet, we have to delete all records with the name and type specified in the `utils.DnsRecord` object and then create a record for each of the `utils.DnsRecord.Records` items.

**Comment by weppos** [comment]
Oh, got it. Thanks.

**Comment by janeczku** [comment]
NP 👍

**Comment by alena1108** [comment]
LGTM

**Comment by weppos** [comment]
We are still experiencing a very large amount of requests (in the order of thousands) per day per domain managed by Rancher.

Do you confirm that the throttling is up and running? Please forgive me if I'm not completely familiar with the platform, but are Rancher users supposed to upgrade their setup, or is the management centralized by the platform (aka updates are immediately released to all the users)?

/cc @jmatsushita

**Comment by vincent99** [comment]
@weppos Sorry for the trouble... Rancher is user-managed/on-premise so there's going to be a long tail of upgrades.  We're also OSS so we have no idea who the users are to ask any specific ones to upgrade.  Are you seeing the total volume go down in general?

There is a central(-ish) "catalog" repo that users read from to get the Docker templates for the version of applications they want to install, and when there's a newer version it shows a fairly prominent "Upgrade Available" button.  

image

(Ignore that the status is red because I didn't put in real credentials...)

- @janeczku Can you confirm & double check what version of the template the fix got released with (seems to be `v0.6.0-rancher1`)?  Then we can change catalog metadata to cause older versions to be available at all anymore.

- Are we sure the fix a) actually worked and b) reduces the call volume to something dnsimple considers acceptable?  Or is thousands per day what we "expect" it should be doing? (e.g. one call a minute to check state is 1,440/day/install)

- Is there anything we can do to make it better either on our side, or perhaps proposing tweaks to their API that would allow what we need to be done with less calls?

**Comment by janeczku** [comment]
@weppos 
* The latest template (v0.6.0-rancher1) hard limits API requests to the theoretical limit of 5400 req/hour. This was verified by QA tests. Even in heavy operations i would not expect more than 100-200 requests per hour effectively.
* My guess is that your customer is either running an older version of the template or he may have multiple instances of the service running concurrently and configured to use the same domain.
* Does the v1 DNSimple API enforce the rate limit by throwing an error when it's exceeded? One solution from our side would be implement a backoff algorithm acting on those errors. Though this would work much better if your API would enforce a per minute rate limit rather then the hourly limit.

**Comment by weppos** [comment]
@jmatsushita can you please follow up and check if you are using the correct version?

> Does the v1 DNSimple API enforce the rate limit by throwing an error when it's exceeded?

Yes, it does. However, the limit is quite high (we did not have it in v1, we introduced in v2 and we set an high limit in v1 for compatibility).

> Another solution would be to switch the service to the v2 API and then use the X-RateLimit-Remaining header to throttle requests on the account instead of the application instance level.

Yes, admittedly I have been considering to provide a patch for months. It's just that I had several other issues in the middle. :/

**Pull request merged**
